### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by favoyang** [Halodi/halodi-unity-package-creator#10]
As title.

**Comment by jespersmith** [comment]
Unsure why the license doesn't get picked up. I have a license file in the package

https://github.com/Halodi/halodi-unity-package-creator/blob/master/Packages/halodi-unity-package-creator/LICENSE.md

and in the package.json 

`"license": "Apache-2.0"`

**Comment by favoyang** [comment]
It was reading from the GitHub license API, which parses the License.md from the repository root path. I will fallback to the license of package.json then.
